### ISSUE TITLE
innstalling this library

### ISSUE THREAD

**Issue by urantiani** [openmusic-project/OM-pm2#2]
greetings

I am a newbie in innstalling external libraries . How does one get OM to accept this type of libraries? 
I am on OM 6.15

all the best 
Nikolai 

![error 1](https://user-images.githubusercontent.com/43235765/62171350-edbd8980-b32e-11e9-949f-42907a0f3bbf.jpg)

**Comment by j-bresson** [comment]
Hello Nikolai, you should get the bundled releases from here : https://github.com/openmusic-project/OM-pm2/releases

Using the cloned repository does not work because the OM library must be named "OM-pm2" (not "OM-pm2-master")

**Comment by j-bresson** [comment]
ps. Note that you will need to install an authorized version of pm2 to get anything interesting out of this library.

**Comment by urantiani** [comment]
AAH !! thank you for the swift answer !!  
I see so there is a own page for releases of those that end without a "master"

Thank you so much 
Niko

**Comment by urantiani** [comment]
Ooh I see now . This is all to be found onn Ircams pages haha!
